version: '3'

services:
  socialnetwork:
    container_name: socialnetwork
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./socialnetwork:/socialnetwork
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
      - minio

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./dotenv_files/.env

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./minio:/minio_files
    command: 'minio server /minio_files --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  minio_data:
    driver: local
